name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      run_integration:
        description: "Run integration tests (hits Jikan API)"
        default: "false"
        required: false
  schedule:
    - cron: "0 3 * * *" # nightly at 03:00 UTC

jobs:
  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        run: npm ci
      - name: Run unit tests
        run: npm run test:unit

  integration:
    name: Integration tests
    # Run on schedule, or when manually triggered with input flag
    if: github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.run_integration == 'true')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install
        run: npm ci
      - name: Run integration tests
        run: npm run test:integration