name: Deploy Pages Preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: pages-preview-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: app
        run: npm ci

      - name: Build (relative base for nested preview path)
        working-directory: app
        run: npm run build -- --base=./

      - name: Include legacy app
        run: mkdir -p app/dist/legacy && cp seasonal-random-anime/index.html app/dist/legacy/index.html

      - name: Deploy PR preview to gh-pages under previews/pr-N
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: app/dist
          target-folder: previews/pr-${{ github.event.pull_request.number }}
          clean: false
          clean-exclude: |
            previews/**
          single-commit: false

  comment:
    if: ${{ always() && github.event.pull_request.head.repo.full_name == github.repository }}
    runs-on: ubuntu-latest
    needs: build-and-deploy
    steps:
      - name: Comment preview URL on PR
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.issue.number;
            const url = `https://${context.repo.owner}.github.io/${context.repo.repo}/previews/pr-${pr}/`;
            const body = `✅ Preview deployed: ${url}`;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
        env: {}


