name: Deploy Pages (Production)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: 'pages-prod'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (push)
        if: github.event_name == 'push'
        uses: actions/checkout@v4

      - name: Checkout main (manual dispatch)
        if: github.event_name == 'workflow_dispatch'
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: app
        run: npm ci

      - name: Build (production base from Vite config)
        working-directory: app
        run: npm run build

      - name: Include legacy app
        run: mkdir -p app/dist/legacy && cp seasonal-random-anime/index.html app/dist/legacy/index.html

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: app/dist
          clean: true
          clean-exclude: |
            previews/**
          single-commit: true