name: Deploy Pages (Production)

on:
  pull_request:
    types: [ closed ]
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: 'pages-prod'
  cancel-in-progress: true

jobs:
  build-and-deploy:
    if: github.event_name != 'pull_request' || github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout merged commit (merge or squash)
        if: github.event_name == 'pull_request' && github.event.pull_request.merge_commit_sha != null
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Checkout base branch tip (rebase merge)
        if: github.event_name == 'pull_request' && github.event.pull_request.merge_commit_sha == null
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}

      - name: Checkout main (manual dispatch)
        if: github.event_name != 'pull_request'
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: app
        run: npm ci

      - name: Build (production base from Vite config)
        working-directory: app
        run: npm run build

      - name: Include legacy app
        run: mkdir -p app/dist/legacy && cp seasonal-random-anime/index.html app/dist/legacy/index.html

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: app/dist
          clean: true
          clean-exclude: |
            previews/**
          single-commit: true